services:
  music-hub:
    build: .
    container_name: music-hub
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./frontend/public:/app/frontend_public
    restart: unless-stopped
    environment:
      - PORT=3000
      - DATABASE_DIR=/app/data
